
												---LOCATION TABLE---
CREATE TABLE LOCATION(
LOCATION_ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
LOCATION_NAME TEXT NOT NULL,
SIZE TEXT)

STRICT;



												---DRIVER TABLE---
CREATE TABLE DRIVER(
DRIVER_ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
FIRST_NAME TEXT NOT NULL,
LAST_NAME TEXT NOT NULL,
DOB TEXT NOT NULL,
PHONE_NUMBER TEXT NOT NULL,
EMAIL TEXT NOT NULL,
ADDRESS_LINE TEXT NOT NULL,
CITY TEXT NOT NULL,
STATE TEXT NOT NULL,
ZIP TEXT NOT NULL,
AVG_RATING INTEGER)

STRICT;


												---USER TABLE---
CREATE TABLE USER(
USER_ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
FIRST_NAME TEXT NOT NULL,
LAST_NAME TEXT NOT NULL,
DOB TEXT NOT NULL,
PHONE_NUMBER TEXT NOT NULL,
EMAIL TEXT NOT NULL,
ADDRESS_LINE TEXT NOT NULL,
CITY TEXT NOT NULL,
STATE TEXT NOT NULL,
ZIP TEXT NOT NULL,
AVG_RATING REAL)

STRICT;

												---RIDE TABLE---
CREATE TABLE RIDE(
RIDE_ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
SERVICE_TYPE TEXT NOT NULL,
VEHICLE_TYPE TEXT NOT NULL,
CAR_COLOR TEXT NOT NULL,
LICENSE_PLATE_NUMBER TEXT NOT NULL,
RIDE_COST REAL NOT NULL,
START_LOCATION TEXT NOT NULL,
END_LOCATION TEXT NOT NULL,
RIDE_DATE TEXT NOT NULL,
RIDE_BEG_TIME TEXT NOT NULL,
RIDE_END_TIME TEXT NOT NULL,
DRIVER_ID INTEGER NOT NULL,
USER_ID INTEGER NOT NULL,
USER_RATING INTEGER,
DRIVER_RATING INTEGER,
CANCELLED TEXT NOT NULL,
CONSTRAINT FK_RIDE_USER FOREIGN KEY (USER_ID)REFERENCES USER(USER_ID)
CONSTRAINT FK_RIDE_DRIVER FOREIGN KEY (DRIVER_ID)REFERENCES DRIVER(DRIVER_ID)
)
STRICT;


										---DRIVER_LOCATION TABLE---
CREATE TABLE DRIVER_LOCATION(
DRIVER_LOCATION_ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
DRIVER_ID INTEGER NOT NULL,
LOCATION_ID INTEGER NOT NULL,
CONSTRAINT FK_DRIVER_LOCATION_DRIVER FOREIGN KEY (DRIVER_ID)REFERENCES DRIVER(DRIVER_ID)
CONSTRAINT FK_DRIVER_LOCATION_LOCATION FOREIGN KEY (LOCATION_ID)REFERENCES LOCATION(LOCATION_ID)
)
STRICT;



